version: '3.7'

services:
  web:
    build: ./nginx
    container_name: ${PROJECT_NAME}
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      # - "${NGINX_HOST_HTTPS_PORT}:443"
      # - "${NGINX_BACK_END_PORT}:${NGINX_BACK_END_PORT}"
      # - "${NGINX_FRONT_END_PORT}:${NGINX_FRONT_END_PORT}"
    environment:
      TZ: "Asia/Tokyo"
    networks:
      default:
        ipv4_address: ${SERVICE_NETWORK_IP}

networks:
  default:
    external:
      name: ${NETWORK_NAME}
