version: '3.7'

services:
  web:
    build: ./nginx
    container_name: ${PROJECT_NAME}
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    environment:
      TZ: "Asia/Tokyo"
    networks:
      default:
        ipv4_address: ${SERVICE_NETWORK_IP}

networks:
  default:
    external:
      name: ${NETWORK_NAME}
